# Generated by Django 2.2.6 on 2019-10-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_address', to='accounts.FcAddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'db_table': 'fc_provider',
            },
        ),
        migrations.CreateModel(
            name='FcServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('service_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_services', to='providers.FcProvider')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider', to='services.FcService')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'db_table': 'fc_service_provider',
            },
        ),
        migrations.CreateModel(
            name='FcServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Service Requirement')),
                ('service_required_on', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service requested On')),
                ('expected_start_time', models.CharField(blank=True, max_length=500, null=True, verbose_name='Expected Start Time')),
                ('expected_hours_to_complete', models.CharField(blank=True, max_length=500, null=True, verbose_name='Expected Complete hours')),
                ('total_amount', models.CharField(blank=True, max_length=120, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='new', max_length=120, verbose_name='Status')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=500, null=True, verbose_name='Payment Mode')),
                ('service_deliver_on', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Delivered on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customers.FcCustomer')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_service_request', to='providers.FcServiceProvider')),
            ],
            options={
                'verbose_name': 'Service Request',
                'db_table': 'fc_service_request',
            },
        ),
    ]
