# Generated by Django 2.2.6 on 2019-12-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191230_1216'),
        ('services', '0002_fcservice_avatar'),
        ('providers', '0002_auto_20191231_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FcServiceProvider',
            new_name='FcProviderServices',
        ),
        migrations.AlterModelOptions(
            name='fcproviderservices',
            options={'verbose_name': 'Provider Service'},
        ),
        migrations.AddField(
            model_name='fcprovider',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'disabled')], default='disabled', max_length=8),
        ),
        migrations.AlterModelTable(
            name='fcproviderservices',
            table='fc_provider_services',
        ),
    ]
