# Generated by Django 2.2.6 on 2019-12-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20191231_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcprovider',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fcprovider',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fcprovider',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
