# Generated by Django 2.2.6 on 2019-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20191231_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcprovider',
            name='address',
            field=models.CharField(default='Lagos', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcprovider',
            name='city',
            field=models.CharField(default='Lagos', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcprovider',
            name='name',
            field=models.CharField(default='New', max_length=255),
            preserve_default=False,
        ),
    ]
