# Generated by Django 2.2.6 on 2019-12-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20191231_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcprovider',
            name='state',
            field=models.CharField(default='Lagos', max_length=255),
            preserve_default=False,
        ),
    ]
