# Generated by Django 2.2.6 on 2019-12-31 04:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_auto_20191231_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcprovider',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2),
        ),
    ]
