# Generated by Django 2.2.6 on 2019-12-31 01:20

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcservice',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.service_upload_path),
        ),
    ]
