# Generated by Django 2.2.6 on 2019-12-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'fc_customer',
            },
        ),
        migrations.CreateModel(
            name='FcServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Service Requirement')),
                ('service_required_on', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service requested On')),
                ('expected_start_time', models.CharField(blank=True, max_length=500, null=True, verbose_name='Expected Start Time')),
                ('expected_hours_to_complete', models.CharField(blank=True, max_length=500, null=True, verbose_name='Expected Complete hours')),
                ('total_amount', models.FloatField(blank=True, max_length=120, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('cancel', 'Cancelled'), ('completed', 'Completed')], default='new', max_length=120, verbose_name='Status')),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=500, null=True, verbose_name='Payment Mode')),
                ('service_deliver_on', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Delivered on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customers.FcCustomer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.FcService')),
            ],
            options={
                'verbose_name': 'Service Request',
                'db_table': 'fc_service_request',
            },
        ),
    ]
