# Generated by Django 2.2.6 on 2019-12-30 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcservicerequest',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_service_request', to='providers.FcServiceProvider'),
        ),
        migrations.AddField(
            model_name='fccustomer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='accounts.FcAddress'),
        ),
        migrations.AddField(
            model_name='fccustomer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
