# Generated by Django 2.2.6 on 2019-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_fcservicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcservicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('cancel', 'Cancelled'), ('completed', 'Completed')], default='new', max_length=120, verbose_name='Status'),
        ),
    ]
