# Generated by Django 2.2.6 on 2019-12-31 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191230_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcservicerequest',
            name='expected_start_time',
        ),
        migrations.AddField(
            model_name='fcservicerequest',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fcservicerequest',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(1232, 2332), size=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcservicerequest',
            name='service_required_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Service requested On'),
        ),
    ]
