# Generated by Django 2.2.6 on 2019-12-31 05:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191231_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcservicerequest',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=2),
        ),
    ]
