# Generated by Django 2.2.6 on 2019-11-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191107_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcservicerequest',
            name='total_amount',
            field=models.FloatField(blank=True, max_length=120, null=True, verbose_name='Amount'),
        ),
    ]
